name: Move to In Review when PR is Ready for Review

on:
  pull_request_target:
    types: [review_requested]

jobs:
  ready-for-review-in-progress:
    runs-on: ubuntu-latest
    name: Move to Review Column
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Linked Issues Action
        uses: kin/gh-action-get-linked-issues@v1.0
        id: linked-issues
        with:
          # Required: personal access token with permissions to archive cards
          access-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Output issues
        run: echo "${{ steps.linked-issues.outputs.issues }}"
      - name: Move to In Review
        uses: ./
        with:
          access-token: "${{ secrets.GITHUB_TOKEN }}"
          project-name: "@JuanC-Fandino's backlog"
          target-column: "👀 In review"
          issues: ${{ steps.linked-issues.outputs.issues }}
